### ISSUE TITLE
About the paper: what's the meaning of params in Table 1?

### ISSUE THREAD

**Issue by veepersgit** [Lan1991Xu/ONE_NeurIPS2018#2]
Sorry, have to raise questions beyond the code. 
I just couldn't figure out the meaning of params in Table 1 because the params of network is kind of related with datasets. Besides, the values of params in Table1 is too small.

**Comment by Lan1991Xu** [comment]
Hi, the parameters in Table is the test model parameters. ONE is identical to Vanilla model in the test.
It is true  the params of network is kind of related with datasets. However, since these three datasets(CIFAR10, 100, SVHN) has the same input image resolution (32*32), thus their parameters is equal.
